In [2]:
import pickle
a = open("file","wb")
obj = [11,'PYTHON',b'Love Python']
print(obj)
pickle.dump(obj,a)

[11, 'PYTHON', b'Love Python']


In [3]:
a = open("file","rb")
data = pickle.load(a)
data

[11, 'PYTHON', b'Love Python']

In [5]:
import numpy as np

arr = np.arange(20).reshape(5,4)
print(arr)
print(arr[:3,:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[0 1]
 [4 5]
 [8 9]]


In [19]:
import pandas as pd
a = pd.DataFrame({"Name":["Alex","Amy","Allen","Alice","Ayoung"],"subject_id":["sub1","sub2","sub3","sub4","sub5"],
                  "Marks_scored":[98,90,87,69,78]})
a

Name subject_id  Marks_scored
0    Alex       sub1            98
1     Amy       sub2            90
2   Allen       sub3            87
3   Alice       sub4            69
4  Ayoung       sub5            78

In [22]:
b = pd.DataFrame({"Name":["Billy","Brian","Bran","Bryce","Betty"],"subject_id":["sub2","sub4","sub3","sub6","sub5"],
                  "Marks_scored":[89,80,79,97,88]})
b

Name subject_id  Marks_scored
0  Billy       sub2            89
1  Brian       sub4            80
2   Bran       sub3            79
3  Bryce       sub6            97
4  Betty       sub5            88

In [43]:
x = pd.merge(a, b, left_index=True, right_index=True)
x

Name_x subject_id_x  Marks_scored_x Name_y subject_id_y  Marks_scored_y
0    Alex         sub1              98  Billy         sub2              89
1     Amy         sub2              90  Brian         sub4              80
2   Allen         sub3              87   Bran         sub3              79
3   Alice         sub4              69  Bryce         sub6              97
4  Ayoung         sub5              78  Betty         sub5              88

In [44]:
#Modification

x[x.Marks_scored_x > 80]

Name_x subject_id_x  Marks_scored_x Name_y subject_id_y  Marks_scored_y
0   Alex         sub1              98  Billy         sub2              89
1    Amy         sub2              90  Brian         sub4              80
2  Allen         sub3              87   Bran         sub3              79