In [1]:
import numpy as np
import pandas as pd


In [2]:
df=pd.read_csv("Admission_Predict_Ver.csv")

In [3]:
df.drop(columns=['Serial No.'],inplace=True)
df.head()


GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [4]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)


In [27]:
# from sklearn.preprocessing import StandardScaler
# scalar=StandardScaler()

# x_tranin_trf=scalar.fit_transform(x_train)
# x_test_trf=scalar.transform(x_test)
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler()

x_tranin_trf=scalar.fit_transform(x_train)
x_test_trf=scalar.transform(x_test)

In [28]:
import tensorflow
from tensorflow.keras.layers import Dense

In [29]:
model=tensorflow.keras.Sequential()
model.add(Dense(7,activation='relu',input_dim=7))
model.add(Dense(7,activation='relu'))
model.add(Dense(1,activation='linear'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 7)                 56        
_________________________________________________________________
dense_10 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 8         
Total params: 120
Trainable params: 120
Non-trainable params: 0
_________________________________________________________________


In [41]:
model.compile(optimizer='Adam',loss="mean_squared_error")
history=model.fit(x_tranin_trf,y_train,epochs=100,batch_size=5)

Epoch 1/100
80/80 [==============================] - 0s 663us/step - loss: 0.3939
Epoch 2/100
80/80 [==============================] - 0s 665us/step - loss: 0.0299
Epoch 3/100
80/80 [==============================] - 0s 659us/step - loss: 0.0182
Epoch 4/100
80/80 [==============================] - 0s 607us/step - loss: 0.0145
Epoch 5/100
80/80 [==============================] - 0s 629us/step - loss: 0.0122
Epoch 6/100
80/80 [==============================] - 0s 625us/step - loss: 0.0093
Epoch 7/100
80/80 [==============================] - 0s 595us/step - loss: 0.0081
Epoch 8/100
80/80 [==============================] - 0s 606us/step - loss: 0.0068
Epoch 9/100
80/80 [==============================] - 0s 607us/step - loss: 0.0060
Epoch 10/100
80/80 [==============================] - 0s 603us/step - loss: 0.0055
Epoch 11/100
80/80 [==============================] - 0s 593us/step - loss: 0.0053
Epoch 12/100
80/80 [==============================] - 0s 585us/step - loss: 0.0053
Epoch 13/100


80/80 [==============================] - 0s 586us/step - loss: 0.0036
Epoch 100/100
80/80 [==============================] - 0s 572us/step - loss: 0.0034


In [42]:
print(model.layers[0].weights)
print(model.layers[1].weights)
print(model.layers[2].weights)

[<tf.Variable 'dense_9/kernel:0' shape=(7, 7) dtype=float32, numpy=
array([[ 0.537271  , -0.31758496,  0.5801898 , -0.02792808,  0.2515317 ,
        -0.26754948,  0.2950402 ],
       [ 0.52814335, -0.2830664 ,  0.70943624, -0.30076727, -0.4703935 ,
         0.28758213, -0.3041905 ],
       [-0.2791964 ,  0.19734524,  0.67343163, -0.30189684,  0.12975322,
        -0.47676763, -0.03666298],
       [-0.04039048,  0.4400255 ,  0.73650557, -0.43771788, -0.6709276 ,
         0.15053822,  0.24207816],
       [-0.28944966, -0.279054  ,  0.13799663,  0.3507581 , -0.42386487,
        -0.43731332, -0.11586371],
       [ 0.18414594,  0.46975777,  0.13602607,  0.5603463 ,  0.19478069,
        -0.22913966,  0.204746  ],
       [-0.15407342,  0.19950435,  1.17235   , -0.10673098, -1.1074456 ,
        -0.52531165,  0.7831939 ]], dtype=float32)>, <tf.Variable 'dense_9/bias:0' shape=(7,) dtype=float32, numpy=
array([ 0.3843128 ,  0.126566  , -0.01999614,  0.27413002,  0.06829724,
        0.00721261, -0.

In [46]:
y_pred=model.predict(x_test_trf)
y_pred

array([[0.9698907 ],
       [0.73424274],
       [0.5431979 ],
       [0.9662256 ],
       [0.5602138 ],
       [0.62263054],
       [0.81268394],
       [0.5875509 ],
       [0.5255271 ],
       [0.6335877 ],
       [0.66758823],
       [0.5966896 ],
       [0.52227205],
       [0.7233653 ],
       [0.5391646 ],
       [0.69971335],
       [0.5274507 ],
       [0.6323637 ],
       [0.77164006],
       [0.9109055 ],
       [0.8736655 ],
       [0.8023613 ],
       [0.6856189 ],
       [0.49334657],
       [0.78055567],
       [0.91007733],
       [0.7405379 ],
       [0.7064354 ],
       [0.575803  ],
       [0.65606534],
       [0.73169565],
       [0.98439324],
       [0.54850394],
       [0.9648322 ],
       [0.691336  ],
       [0.72030896],
       [0.82939994],
       [0.8160341 ],
       [0.6738607 ],
       [0.6822252 ],
       [0.8359501 ],
       [0.97100174],
       [0.8423277 ],
       [0.9366146 ],
       [0.580405  ],
       [0.7835609 ],
       [0.76377606],
       [1.012

In [47]:
from sklearn.metrics import r2_score

In [48]:
r2_score(y_test,y_pred)

0.7715583971765312

In [49]:
history.history

{'loss': [0.3939414620399475,
  0.029896652325987816,
  0.018166132271289825,
  0.014508256688714027,
  0.01215380523353815,
  0.009280805476009846,
  0.008121143095195293,
  0.00676193879917264,
  0.006028462201356888,
  0.00549327302724123,
  0.0052726478315889835,
  0.005299463868141174,
  0.004767534323036671,
  0.004615297075361013,
  0.004491076339036226,
  0.004439071752130985,
  0.004312367644160986,
  0.004040224011987448,
  0.004065075423568487,
  0.004029081668704748,
  0.003960158675909042,
  0.0039384691044688225,
  0.003990469966083765,
  0.0037912458647042513,
  0.003794083371758461,
  0.0038092341274023056,
  0.0037301371339708567,
  0.0037134671583771706,
  0.0037017944268882275,
  0.003773486940190196,
  0.0037019255105406046,
  0.0037378070410341024,
  0.003641726914793253,
  0.0037073532585054636,
  0.003672391874715686,
  0.0036596653517335653,
  0.003680943278595805,
  0.003632924286648631,
  0.0035663836169987917,
  0.00373598700389266,
  0.003641954157501459,
  