# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
Data = pd.read_csv('Data.csv')
print(Data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [3]:
X = Data.iloc [:,:-1].values
y = Data.iloc [:,3].values

X
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Taking care of missing data

In [4]:

from sklearn.impute import SimpleImputer
missingValueImputer = SimpleImputer(missing_values=np.nan, strategy='mean')


# missingValueImputer = Imputer (missing_values = 'NaN', strategy = 'mean',axis = 0)

missingValueImputer = missingValueImputer.fit (X[:,1:3])
# update values of X with new values
X[:,1:3] = missingValueImputer.transform(X[:,1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [5]:
#Independent variable
# from sklearn.preprocessing import LabelEncoder
# X_labelencoder = LabelEncoder()
# X[:, 0] = X_labelencoder.fit_transform(X[:, 0])
# print (X)
#onehot encoder

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [6]:
# for y
from sklearn.preprocessing import LabelEncoder
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[0 1 0 0 1 1 0 1 0 1]


### Encoding the Independent Variable

### Encoding the Dependent Variable

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2,
                                                     random_state = 0)

## Feature Scaling

In [10]:

from sklearn.preprocessing import StandardScaler
independent_scalar = StandardScaler()
X_train[:,3:] = independent_scalar.fit_transform (X_train[:,3:]) #fit and transform
X_test[:,3:] = independent_scalar.transform (X_test[:,3:]) # only transform
# print(X_train)
print(X_test)

[[0.0 1.0 0.0 -1.4588292694047797 -0.9016629672292145]
 [0.0 1.0 0.0 1.9849644157474868 2.1398108220673926]]
