In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Health.csv')
data

Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0      White        186.0         90.0                  Yes
1    African        185.0         98.0                   No
2      White        175.0         80.0                   No
3      White        180.0         88.0                  Yes
4      Asian        178.0          NaN                   No
5      Asian        172.0         72.0                  Yes
6    African        178.0         75.0                   No
7      White          NaN         89.0                  Yes
8    African        186.0         90.0                  Yes
9    African       1000.0          1.0                  Yes
10     White         10.0       1000.0                   no

In [3]:
x = data.iloc[:,:-1].values
y = data.iloc[:,3].values
print(x)
print(y)

[['White' 186.0 90.0]
 ['African' 185.0 98.0]
 ['White' 175.0 80.0]
 ['White' 180.0 88.0]
 ['Asian' 178.0 nan]
 ['Asian' 172.0 72.0]
 ['African' 178.0 75.0]
 ['White' nan 89.0]
 ['African' 186.0 90.0]
 ['African' 1000.0 1.0]
 ['White' 10.0 1000.0]]
['Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'no']


In [4]:
from sklearn.impute import SimpleImputer

missing_values = SimpleImputer(missing_values=np.nan,strategy='mean').fit(x[:,1:3])
x[:,1:3] = missing_values.transform(x[:,1:3])
x

array([['White', 186.0, 90.0],
       ['African', 185.0, 98.0],
       ['White', 175.0, 80.0],
       ['White', 180.0, 88.0],
       ['Asian', 178.0, 168.3],
       ['Asian', 172.0, 72.0],
       ['African', 178.0, 75.0],
       ['White', 245.0, 89.0],
       ['African', 186.0, 90.0],
       ['African', 1000.0, 1.0],
       ['White', 10.0, 1000.0]], dtype=object)

In [5]:

from sklearn.preprocessing import LabelEncoder
x_labelencoder = LabelEncoder()
x[:, 0] = x_labelencoder.fit_transform(x[:, 0])
print (x)

[[2 186.0 90.0]
 [0 185.0 98.0]
 [2 175.0 80.0]
 [2 180.0 88.0]
 [1 178.0 168.3]
 [1 172.0 72.0]
 [0 178.0 75.0]
 [2 245.0 89.0]
 [0 186.0 90.0]
 [0 1000.0 1.0]
 [2 10.0 1000.0]]


In [6]:
from sklearn.preprocessing import LabelEncoder
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[1 0 0 1 0 1 0 1 1 1 2]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (x, y, test_size = 0.2,
                                                     random_state = 0)

In [8]:

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform (X_train) 
# X_test = sc.transform (X_test)
# print(X_train,"Standard scaler")
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
train = sc.fit_transform (X_train) 
test = sc.transform (X_test)
print(train)




[[1.         0.         1.        ]
 [0.         0.71489362 0.00323276]
 [0.         0.74468085 0.02801724]
 [1.         1.         0.01831897]
 [0.         0.74893617 0.01939655]
 [1.         0.72340426 0.01724138]
 [1.         0.74893617 0.01939655]
 [0.5        0.6893617  0.        ]]


In [9]:
print(test)

[[ 0.5         0.71489362  0.10377155]
 [ 0.          4.21276596 -0.07650862]
 [ 1.          0.70212766  0.00862069]]


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform (X_train) 
X_test = sc.transform (X_test)
print(X_train,"Standard scaler")

[[ 0.94387981 -2.49076576  2.64483605]
 [-1.21355975  0.16184056 -0.41421159]
 [-1.21355975  0.27236583 -0.33814878]
 [ 0.94387981  1.21972523 -0.36791249]
 [-1.21355975  0.28815515 -0.36460541]
 [ 0.94387981  0.19341921 -0.37121956]
 [ 0.94387981  0.28815515 -0.36460541]
 [-0.13483997  0.06710462 -0.42413282]] Standard scaler
