In [1]:
import numpy as np
import pandas as pd

In [2]:
data  = pd.read_csv('Salary_Data.csv')
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
print(X,y)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]] [ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1/3,random_state = 42)

In [22]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X,y)
print(type(X))

<class 'numpy.ndarray'>


In [15]:
y_pred = regressor.predict(X)

In [16]:
m = regressor.coef_
m

array([9449.96232146])

In [17]:
c = regressor.intercept_
c

25792.20019866871

In [29]:
# ax = [[1,2,3,4,5]]
# ay = [[3,4,2,4,5]]
# ax = np.array(ax)
# # ay = np.array(ay)

data  = pd.read_csv('sample.csv')
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
print(X,y)

[[1]
 [2]
 [3]
 [4]
 [5]] [3 4 2 4 5]


In [30]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X,y)


LinearRegression()

In [31]:
m = regressor.coef_
m

array([0.4])

In [32]:
c = regressor.intercept_
c

2.4000000000000004